name: modi
description: Study Management
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+39

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  table_calendar: ^3.0.9 # 캘린더
  intl: ^0.18.1 # 다국어 처리
  sentry_flutter: ^7.18.0 # 로깅
  firebase_core_web: ^2.11.4
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  firebase_analytics: ^10.8.5
  flutter_local_notifications: ^15.1.0+1
  font_awesome_flutter: ^10.5.0 # 아이콘
  page_view_dot_indicator: ^2.3.0
  dio: 5.3.2
  flutter_secure_storage: ^8.0.0
  go_router: 10.1.0
  flutter_native_splash: ^2.3.5
  kakao_flutter_sdk: ^1.7.0
  flutter_launcher_icons: ^0.13.1
  provider: ^6.1.1
  http: ^1.1.2
  flutter_dotenv: ^5.1.0

  carousel_slider: ^4.2.1 # 캐러셀 슬라이드

  retrofit: ^4.0.3
  retrofit_generator: ^8.0.1
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.8
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  get_it: ^7.6.6
  jwt_decoder: ^2.0.1
  image_picker: ^1.0.7
  bottom_picker: ^2.3.3
  fluttertoast: ^8.0.8
  change_app_package_name: ^1.1.0
  sign_in_with_apple: ^5.0.0
  logger: ^2.0.2+1
  device_info_plus: ^9.1.2
  social_share: ^2.3.1
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  uni_links: ^0.5.1
  yaml: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/login/
    - asset/search_category/
    - asset/study_manage/
    - asset/fonts/
    - asset/share/
    - .local.env
    - shorebird.yaml
    - pubspec.yaml

  fonts:
    - family: Pretendard
      fonts:
        - asset: asset/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: asset/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: asset/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: asset/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: asset/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: asset/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: asset/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: asset/fonts/Pretendard-Black.ttf
          weight: 900
