// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:10829227760:web:02ecfab71d1befda4a4435',
    messagingSenderId: '10829227760',
    projectId: 'modi-25afe',
    authDomain: 'modi-25afe.firebaseapp.com',
    storageBucket: 'modi-25afe.appspot.com',
    measurementId: 'G-0BPFW3MLJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:10829227760:android:a206337630119c804a4435',
    messagingSenderId: '10829227760',
    projectId: 'modi-25afe',
    storageBucket: 'modi-25afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:10829227760:ios:60c701e94fb30a6e4a4435',
    messagingSenderId: '10829227760',
    projectId: 'modi-25afe',
    storageBucket: 'modi-25afe.appspot.com',
    iosBundleId: 'com.modiapp.modi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:10829227760:ios:3d8ad6f13ce6cd354a4435',
    messagingSenderId: '10829227760',
    projectId: 'modi-25afe',
    storageBucket: 'modi-25afe.appspot.com',
    iosBundleId: 'com.example.withing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:10829227760:web:ba3e673d7e823a744a4435',
    messagingSenderId: '10829227760',
    projectId: 'modi-25afe',
    authDomain: 'modi-25afe.firebaseapp.com',
    storageBucket: 'modi-25afe.appspot.com',
    measurementId: 'G-QVGYFHT2R5',
  );

}